---
sudo: false
language: fortran

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gfortran-7

cache:
  directories:
    # - $HOME/...

matrix:
  fast_finish: true
  include:
  allow_failures:

before_install:
    - pwd
    - if [[ -v CC ]]; then printenv CC; fi
    - if [[ -v CXX ]]; then printenv CXX; fi
    - if [[ -x `which gcc` ]]; then gcc --version; fi
    - if [[ -x `which g++` ]]; then g++ --version; fi
    - if [[ -x `which gcc-7` ]]; then gcc-7 --version; CC=gcc-7; fi
    - if [[ -x `which g++-7` ]]; then g++-7 --version; CXX=g++-7; fi
    - if [[ -x `which gcc-6` ]]; then gcc-6 --version; CC=gcc-6; fi
    - if [[ -x `which g++-6` ]]; then g++-6 --version; CXX=g++-6; fi
    - if [[ -x `which gcc-5` ]]; then gcc-5 --version; CC=gcc-5; fi
    - if [[ -x `which g++-5` ]]; then g++-5 --version; CXX=g++-5; fi
    - if [[ -x `which gcc-4.9` ]]; then gcc-4.9 --version; CC=gcc-4.9; fi
    - if [[ -x `which g++-4.9` ]]; then g++-4.9 --version; CXX=g++-4.9; fi
    - if [[ -v CC ]]; then printenv CC; fi
    - if [[ -v CXX ]]; then printenv CXX; fi
    - if [[ -x `which $CC` ]]; then $CC --version; fi
    - if [[ -x `which $CXX` ]]; then $CXX --version; fi

# install:

# before_script:

script:
    - gfortran-7 --version
    - gfortran --version
    - env

# after_success:
