---
sudo: false
language: c # fortran

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gfortran-7

cache:
  directories:
    # - $HOME/...

matrix:
  fast_finish: true
  include:
  allow_failures:

before_install:
    - pwd
    - if [[ -v CC ]]; then printenv CC; fi
    - if [[ -x `which gcc` ]]; then gcc --version; fi
    - if [[ -x `which gfortran` ]]; then gfortran --version; fi
    - if [[ -x `which gcc-7` ]]; then gcc-7 --version; fi
    - if [[ -x `which gfortran-7` ]]; then gfortran-7 --version; fi
    - if [[ -x `which gcc-6` ]]; then gcc-6 --version; fi
    - if [[ -x `which gfortran-6` ]]; then gfortran-6 --version; fi
    - if [[ -x `which gcc-5` ]]; then gcc-5 --version; fi
    - if [[ -x `which gfortran-5` ]]; then gfortran-5 --version; fi
    - if [[ -x `which gcc-4.9` ]]; then gcc-4.9 --version; fi
    - if [[ -x `which gfortran-4.9` ]]; then gfortran-4.9 --version; fi

# install:

# before_script:

script:
    - gfortran-7 --version
    - gfortran --version
    - env

# after_success:
